// <auto-generated />
using System;
using Mayflower.Core.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mayflower.Data.Migrations
{
    [DbContext(typeof(MayflowerContext))]
    [Migration("20230429002735_InitialCreationAndSeed")]
    partial class InitialCreationAndSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mayflower.DomainModels.FinancialAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FinancialAccountTheme")
                        .HasColumnType("int")
                        .HasColumnName("FinancialAccountThemeId");

                    b.Property<int>("FinancialInstitutionId")
                        .HasColumnType("int");

                    b.Property<string>("NickName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("FinancialAccountTheme");

                    b.HasIndex("FinancialInstitutionId");

                    b.ToTable("FinancialAccount", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FinancialAccountTheme = 2,
                            FinancialInstitutionId = 1,
                            NickName = "Primary Checking",
                            Number = "1032497347"
                        },
                        new
                        {
                            Id = 2,
                            FinancialAccountTheme = 2,
                            FinancialInstitutionId = 1,
                            NickName = "Bill Pay Account",
                            Number = "1054452618"
                        },
                        new
                        {
                            Id = 3,
                            FinancialAccountTheme = 1,
                            FinancialInstitutionId = 1,
                            NickName = "Primary Savings",
                            Number = "2132880598"
                        },
                        new
                        {
                            Id = 4,
                            FinancialAccountTheme = 1,
                            FinancialInstitutionId = 1,
                            NickName = "Xmas Fund",
                            Number = "2133086542"
                        },
                        new
                        {
                            Id = 5,
                            FinancialAccountTheme = 1,
                            FinancialInstitutionId = 1,
                            NickName = "Me-want Fund",
                            Number = "2141652087"
                        },
                        new
                        {
                            Id = 6,
                            FinancialAccountTheme = 1,
                            FinancialInstitutionId = 1,
                            NickName = "Birthday Fund",
                            Number = "2144275472"
                        },
                        new
                        {
                            Id = 7,
                            FinancialAccountTheme = 1,
                            FinancialInstitutionId = 1,
                            NickName = "Graces Emergency Fund",
                            Number = "2144275977"
                        },
                        new
                        {
                            Id = 8,
                            FinancialAccountTheme = 1,
                            FinancialInstitutionId = 1,
                            NickName = "Landscaping Fund",
                            Number = "2148132695"
                        });
                });

            modelBuilder.Entity("Mayflower.DomainModels.FinancialAccountTheme", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("FinancialAccountTheme", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "None",
                            Value = "None"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Savings",
                            Value = "Savings"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Checking",
                            Value = "Checking"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Marketing",
                            Value = "Marketing"
                        });
                });

            modelBuilder.Entity("Mayflower.DomainModels.FinancialInstitution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NickName")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("FinancialInstitution", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ally Bank",
                            NickName = "Ally"
                        });
                });

            modelBuilder.Entity("Mayflower.DomainModels.RecurrenceDayOfWeek", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("RecurrenceDayOfWeek", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "None",
                            Value = "None"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Sunday",
                            Value = "Sunday"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Monday",
                            Value = "Monday"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tuesday",
                            Value = "Tuesday"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Wednesday",
                            Value = "Wednesday"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Thursday",
                            Value = "Thursday"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Friday",
                            Value = "Friday"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Saturday",
                            Value = "Saturday"
                        });
                });

            modelBuilder.Entity("Mayflower.DomainModels.RecurrenceOrdinal", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("RecurrenceOrdinal", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "None",
                            Value = "None"
                        },
                        new
                        {
                            Id = 1,
                            Name = "First",
                            Value = "First"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Second",
                            Value = "Second"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Third",
                            Value = "Third"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fourth",
                            Value = "Fourth"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Last",
                            Value = "Last"
                        });
                });

            modelBuilder.Entity("Mayflower.DomainModels.RecurrenceTheme", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("RecurrenceTheme", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "No Recurrence",
                            Value = "NoRecurrence"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Daily",
                            Value = "Daily"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Weekly",
                            Value = "Weekly"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Monthly",
                            Value = "Monthly"
                        });
                });

            modelBuilder.Entity("Mayflower.DomainModels.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecurrenceTheme")
                        .HasColumnType("int")
                        .HasColumnName("RecurrenceThemeId");

                    b.Property<int>("ReminderTheme")
                        .HasColumnType("int")
                        .HasColumnName("ReminderThemeId");

                    b.Property<int?>("TransactionFromAccountId")
                        .HasColumnType("int");

                    b.Property<int?>("TransactionToAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WhenToStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RecurrenceTheme");

                    b.HasIndex("ReminderTheme");

                    b.HasIndex("TransactionFromAccountId");

                    b.HasIndex("TransactionToAccountId");

                    b.ToTable("Reminder", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 2800.00m,
                            Description = "iMedia paycheck deposit",
                            RecurrenceTheme = 0,
                            ReminderTheme = 2,
                            TransactionToAccountId = 1,
                            WhenToStart = new DateTime(2023, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 2800.00m,
                            Description = "iMedia paycheck deposit",
                            RecurrenceTheme = 0,
                            ReminderTheme = 2,
                            TransactionToAccountId = 1,
                            WhenToStart = new DateTime(2023, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amount = 76.25m,
                            Description = "water bill",
                            RecurrenceTheme = 0,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 1,
                            WhenToStart = new DateTime(2023, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amount = 650.00m,
                            Description = "mortage payment",
                            RecurrenceTheme = 0,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 1,
                            WhenToStart = new DateTime(2023, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amount = 225.00m,
                            Description = "vectren bill",
                            RecurrenceTheme = 0,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 1,
                            WhenToStart = new DateTime(2023, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Amount = 235.56m,
                            Description = "car payment",
                            RecurrenceTheme = 0,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 1,
                            WhenToStart = new DateTime(2023, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Amount = 18.98m,
                            Description = "Netflix",
                            RecurrenceTheme = 0,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 1,
                            WhenToStart = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Amount = 50m,
                            Description = "Fuel",
                            RecurrenceTheme = 0,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 1,
                            WhenToStart = new DateTime(2023, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Amount = 50m,
                            Description = "Fuel",
                            RecurrenceTheme = 0,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 1,
                            WhenToStart = new DateTime(2023, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Amount = 100m,
                            Description = "Cigarettes",
                            RecurrenceTheme = 0,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 1,
                            WhenToStart = new DateTime(2023, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Amount = 100m,
                            Description = "Cigarettes",
                            RecurrenceTheme = 0,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 1,
                            WhenToStart = new DateTime(2023, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Amount = 120m,
                            Description = "Smoke",
                            RecurrenceTheme = 0,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 1,
                            WhenToStart = new DateTime(2023, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Amount = 120m,
                            Description = "Smoke",
                            RecurrenceTheme = 0,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 1,
                            WhenToStart = new DateTime(2023, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Amount = 90m,
                            Description = "Child support",
                            RecurrenceTheme = 0,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 1,
                            WhenToStart = new DateTime(2023, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Amount = 90m,
                            Description = "Child support",
                            RecurrenceTheme = 0,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 1,
                            WhenToStart = new DateTime(2023, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Amount = 90m,
                            Description = "Child support",
                            RecurrenceTheme = 0,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 1,
                            WhenToStart = new DateTime(2023, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Amount = 90m,
                            Description = "Child support",
                            RecurrenceTheme = 0,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 1,
                            WhenToStart = new DateTime(2023, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Amount = 2.95m,
                            Description = "Child support fee",
                            RecurrenceTheme = 0,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 1,
                            WhenToStart = new DateTime(2023, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            Amount = 2.95m,
                            Description = "Child support fee",
                            RecurrenceTheme = 0,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 1,
                            WhenToStart = new DateTime(2023, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            Amount = 2.95m,
                            Description = "Child support fee",
                            RecurrenceTheme = 0,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 1,
                            WhenToStart = new DateTime(2023, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            Amount = 2.95m,
                            Description = "Child support fee",
                            RecurrenceTheme = 0,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 1,
                            WhenToStart = new DateTime(2023, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            Amount = 1200.00m,
                            Description = "Transfer from Primary Savings|Transfer to Primary Checking",
                            RecurrenceTheme = 0,
                            ReminderTheme = 3,
                            TransactionFromAccountId = 3,
                            TransactionToAccountId = 1,
                            WhenToStart = new DateTime(2023, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            Amount = 100.00m,
                            Description = "Transfer from Primary Checking|Transfer to Xmas Fund",
                            RecurrenceTheme = 0,
                            ReminderTheme = 3,
                            TransactionFromAccountId = 1,
                            TransactionToAccountId = 4,
                            WhenToStart = new DateTime(2023, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            Amount = 1200.00m,
                            Description = "Transfer from Primary Checking|Transfer to Grace's Emergency Fund",
                            RecurrenceTheme = 0,
                            ReminderTheme = 3,
                            TransactionFromAccountId = 1,
                            TransactionToAccountId = 7,
                            WhenToStart = new DateTime(2023, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Mayflower.DomainModels.ReminderTheme", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("ReminderTheme", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "Error",
                            Value = "Error"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Bill Payment",
                            Value = "Bill"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Income",
                            Value = "Income"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Transfer",
                            Value = "Transfer"
                        });
                });

            modelBuilder.Entity("Mayflower.DomainModels.TransactionTheme", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("TransactionTheme", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "None",
                            Value = "None"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Withdraw",
                            Value = "Withdraw"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Deposit",
                            Value = "Deposit"
                        });
                });

            modelBuilder.Entity("Mayflower.DomainModels.FinancialAccount", b =>
                {
                    b.HasOne("Mayflower.DomainModels.FinancialAccountTheme", "_financialAccountTheme")
                        .WithMany()
                        .HasForeignKey("FinancialAccountTheme")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mayflower.DomainModels.FinancialInstitution", "FinancialInstitution")
                        .WithMany()
                        .HasForeignKey("FinancialInstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialInstitution");

                    b.Navigation("_financialAccountTheme");
                });

            modelBuilder.Entity("Mayflower.DomainModels.Reminder", b =>
                {
                    b.HasOne("Mayflower.DomainModels.RecurrenceTheme", "_recurrenceTheme")
                        .WithMany()
                        .HasForeignKey("RecurrenceTheme")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mayflower.DomainModels.ReminderTheme", "_reminderTheme")
                        .WithMany()
                        .HasForeignKey("ReminderTheme")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mayflower.DomainModels.FinancialAccount", "TransactionFromAccount")
                        .WithMany()
                        .HasForeignKey("TransactionFromAccountId");

                    b.HasOne("Mayflower.DomainModels.FinancialAccount", "TransactionToAccount")
                        .WithMany()
                        .HasForeignKey("TransactionToAccountId");

                    b.Navigation("TransactionFromAccount");

                    b.Navigation("TransactionToAccount");

                    b.Navigation("_recurrenceTheme");

                    b.Navigation("_reminderTheme");
                });
#pragma warning restore 612, 618
        }
    }
}
