// <auto-generated />
using System;
using Mayflower.Core.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mayflower.Core.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MayflowerContext))]
    [Migration("20230819040945_AddedBalancePropertiesToAccount")]
    partial class AddedBalancePropertiesToAccount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mayflower.Core.DomainModels.FinancialAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AvailableBalance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("FinancialAccountTheme")
                        .HasColumnType("int")
                        .HasColumnName("FinancialAccountThemeId");

                    b.Property<int>("FinancialInstitutionId")
                        .HasColumnType("int");

                    b.Property<decimal>("LedgerBalance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NickName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("WhenLastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FinancialAccountTheme");

                    b.HasIndex("FinancialInstitutionId");

                    b.ToTable("FinancialAccount", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableBalance = 0m,
                            FinancialAccountTheme = 2,
                            FinancialInstitutionId = 1,
                            LedgerBalance = 0m,
                            NickName = "Primary Checking",
                            Number = "1032497347",
                            WhenLastUpdated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            AvailableBalance = 0m,
                            FinancialAccountTheme = 2,
                            FinancialInstitutionId = 1,
                            LedgerBalance = 0m,
                            NickName = "Bill Pay Account",
                            Number = "1054452618",
                            WhenLastUpdated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            AvailableBalance = 0m,
                            FinancialAccountTheme = 1,
                            FinancialInstitutionId = 1,
                            LedgerBalance = 0m,
                            NickName = "Primary Savings",
                            Number = "2132880598",
                            WhenLastUpdated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            AvailableBalance = 0m,
                            FinancialAccountTheme = 1,
                            FinancialInstitutionId = 1,
                            LedgerBalance = 0m,
                            NickName = "Xmas Fund",
                            Number = "2133086542",
                            WhenLastUpdated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5,
                            AvailableBalance = 0m,
                            FinancialAccountTheme = 1,
                            FinancialInstitutionId = 1,
                            LedgerBalance = 0m,
                            NickName = "Me-want Fund",
                            Number = "2141652087",
                            WhenLastUpdated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 6,
                            AvailableBalance = 0m,
                            FinancialAccountTheme = 1,
                            FinancialInstitutionId = 1,
                            LedgerBalance = 0m,
                            NickName = "Birthday Fund",
                            Number = "2144275472",
                            WhenLastUpdated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 7,
                            AvailableBalance = 0m,
                            FinancialAccountTheme = 1,
                            FinancialInstitutionId = 1,
                            LedgerBalance = 0m,
                            NickName = "Graces Emergency Fund",
                            Number = "2144275977",
                            WhenLastUpdated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 8,
                            AvailableBalance = 0m,
                            FinancialAccountTheme = 1,
                            FinancialInstitutionId = 1,
                            LedgerBalance = 0m,
                            NickName = "Landscaping Fund",
                            Number = "2148132695",
                            WhenLastUpdated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Mayflower.Core.DomainModels.FinancialAccountTheme", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("FinancialAccountTheme", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "None",
                            Value = "None"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Savings",
                            Value = "Savings"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Checking",
                            Value = "Checking"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Marketing",
                            Value = "Marketing"
                        });
                });

            modelBuilder.Entity("Mayflower.Core.DomainModels.FinancialInstitution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NickName")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("FinancialInstitution", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ally Bank",
                            NickName = "Ally"
                        });
                });

            modelBuilder.Entity("Mayflower.Core.DomainModels.RecurrenceDayOfWeek", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("RecurrenceDayOfWeek", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "Sunday",
                            Value = "Sunday"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Monday",
                            Value = "Monday"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tuesday",
                            Value = "Tuesday"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Wednesday",
                            Value = "Wednesday"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Thursday",
                            Value = "Thursday"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Friday",
                            Value = "Friday"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Saturday",
                            Value = "Saturday"
                        });
                });

            modelBuilder.Entity("Mayflower.Core.DomainModels.RecurrenceOrdinal", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("RecurrenceOrdinal", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "None",
                            Value = "None"
                        },
                        new
                        {
                            Id = 1,
                            Name = "First",
                            Value = "First"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Second",
                            Value = "Second"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Third",
                            Value = "Third"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fourth",
                            Value = "Fourth"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Last",
                            Value = "Last"
                        });
                });

            modelBuilder.Entity("Mayflower.Core.DomainModels.RecurrenceTheme", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("RecurrenceTheme", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "No Recurrence",
                            Value = "NoRecurrence"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Daily",
                            Value = "Daily"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Weekly",
                            Value = "Weekly"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Monthly",
                            Value = "Monthly"
                        });
                });

            modelBuilder.Entity("Mayflower.Core.DomainModels.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecurrenceDayOfMonth")
                        .HasColumnType("int");

                    b.Property<int?>("RecurrenceDayOfWeek")
                        .HasColumnType("int")
                        .HasColumnName("RecurrenceDayOfWeekId");

                    b.Property<int>("RecurrenceInterval")
                        .HasColumnType("int");

                    b.Property<int>("RecurrenceOrdinal")
                        .HasColumnType("int")
                        .HasColumnName("RecurrenceOrdinalId");

                    b.Property<int>("RecurrenceTheme")
                        .HasColumnType("int")
                        .HasColumnName("RecurrenceThemeId");

                    b.Property<int>("ReminderTheme")
                        .HasColumnType("int")
                        .HasColumnName("ReminderThemeId");

                    b.Property<int?>("TransactionFromAccountId")
                        .HasColumnType("int");

                    b.Property<int?>("TransactionToAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("WhenExpires")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenOccurs")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RecurrenceDayOfWeek");

                    b.HasIndex("RecurrenceOrdinal");

                    b.HasIndex("RecurrenceTheme");

                    b.HasIndex("ReminderTheme");

                    b.HasIndex("TransactionFromAccountId");

                    b.HasIndex("TransactionToAccountId");

                    b.ToTable("Reminder", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 645.33m,
                            Description = "Lakeview Mortgage Payment",
                            RecurrenceDayOfMonth = 10,
                            RecurrenceInterval = 1,
                            RecurrenceOrdinal = 0,
                            RecurrenceTheme = 3,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 2,
                            WhenOccurs = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 400m,
                            Description = "Old National Car Payment",
                            RecurrenceDayOfMonth = 7,
                            RecurrenceInterval = 1,
                            RecurrenceOrdinal = 0,
                            RecurrenceTheme = 3,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 2,
                            WhenOccurs = new DateTime(2023, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amount = 120m,
                            Description = "Synchrony/CareCredit Vet Card",
                            RecurrenceDayOfMonth = 2,
                            RecurrenceInterval = 1,
                            RecurrenceOrdinal = 0,
                            RecurrenceTheme = 3,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 2,
                            WhenOccurs = new DateTime(2023, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amount = 71m,
                            Description = "Astound Broadband Internet",
                            RecurrenceDayOfMonth = 24,
                            RecurrenceInterval = 1,
                            RecurrenceOrdinal = 0,
                            RecurrenceTheme = 3,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 2,
                            WhenOccurs = new DateTime(2023, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amount = 12.95m,
                            Description = "Walmart +",
                            RecurrenceDayOfMonth = 8,
                            RecurrenceInterval = 1,
                            RecurrenceOrdinal = 0,
                            RecurrenceTheme = 3,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 2,
                            WhenOccurs = new DateTime(2023, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Amount = 1.99m,
                            Description = "Google Cloud Storage",
                            RecurrenceDayOfMonth = 7,
                            RecurrenceInterval = 1,
                            RecurrenceOrdinal = 0,
                            RecurrenceTheme = 3,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 2,
                            WhenOccurs = new DateTime(2023, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Amount = 27.81m,
                            Description = "Pretty Litter",
                            RecurrenceDayOfWeek = 5,
                            RecurrenceInterval = 3,
                            RecurrenceOrdinal = 0,
                            RecurrenceTheme = 2,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 2,
                            WhenOccurs = new DateTime(2023, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Amount = 19.99m,
                            Description = "Netflix",
                            RecurrenceDayOfMonth = 7,
                            RecurrenceInterval = 1,
                            RecurrenceOrdinal = 0,
                            RecurrenceTheme = 3,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 2,
                            WhenOccurs = new DateTime(2023, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Amount = 9.99m,
                            Description = "Paramount +",
                            RecurrenceDayOfMonth = 10,
                            RecurrenceInterval = 1,
                            RecurrenceOrdinal = 0,
                            RecurrenceTheme = 3,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 2,
                            WhenOccurs = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Amount = 60m,
                            Description = "Google Fi Mobile Phone",
                            RecurrenceDayOfMonth = 15,
                            RecurrenceInterval = 1,
                            RecurrenceOrdinal = 0,
                            RecurrenceTheme = 3,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 2,
                            WhenOccurs = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Amount = 15.99m,
                            Description = "HBO Max",
                            RecurrenceDayOfMonth = 16,
                            RecurrenceInterval = 1,
                            RecurrenceOrdinal = 0,
                            RecurrenceTheme = 3,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 2,
                            WhenOccurs = new DateTime(2023, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Amount = 15.99m,
                            Description = "Amazon Music",
                            RecurrenceDayOfMonth = 17,
                            RecurrenceInterval = 1,
                            RecurrenceOrdinal = 0,
                            RecurrenceTheme = 3,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 2,
                            WhenOccurs = new DateTime(2023, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Amount = 152.08m,
                            Description = "EnerBank/Regions HVAC Payment",
                            RecurrenceDayOfMonth = 25,
                            RecurrenceInterval = 1,
                            RecurrenceOrdinal = 0,
                            RecurrenceTheme = 3,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 2,
                            WhenOccurs = new DateTime(2023, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Amount = 4.99m,
                            Description = "Peacock",
                            RecurrenceDayOfMonth = 26,
                            RecurrenceInterval = 1,
                            RecurrenceOrdinal = 0,
                            RecurrenceTheme = 3,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 2,
                            WhenOccurs = new DateTime(2023, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Amount = 10.99m,
                            Description = "Disney +",
                            RecurrenceDayOfMonth = 26,
                            RecurrenceInterval = 1,
                            RecurrenceOrdinal = 0,
                            RecurrenceTheme = 3,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 2,
                            WhenOccurs = new DateTime(2023, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Amount = 205.89m,
                            Description = "Nelnet Student Loan",
                            RecurrenceDayOfMonth = 28,
                            RecurrenceInterval = 1,
                            RecurrenceOrdinal = 0,
                            RecurrenceTheme = 3,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 2,
                            WhenOccurs = new DateTime(2023, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Amount = 100m,
                            Description = "Chandler Water",
                            RecurrenceDayOfMonth = 20,
                            RecurrenceInterval = 1,
                            RecurrenceOrdinal = 0,
                            RecurrenceTheme = 3,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 2,
                            WhenOccurs = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Amount = 250m,
                            Description = "Centerpoint Gas & Electric",
                            RecurrenceDayOfMonth = 28,
                            RecurrenceInterval = 1,
                            RecurrenceOrdinal = 0,
                            RecurrenceTheme = 3,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 2,
                            WhenOccurs = new DateTime(2023, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            Amount = 50m,
                            Description = "Cricket Wireless",
                            RecurrenceDayOfMonth = 30,
                            RecurrenceInterval = 1,
                            RecurrenceOrdinal = 0,
                            RecurrenceTheme = 3,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 2,
                            WhenOccurs = new DateTime(2023, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            Amount = 91.50m,
                            Description = "Root Car Insurance",
                            RecurrenceDayOfMonth = 30,
                            RecurrenceInterval = 1,
                            RecurrenceOrdinal = 0,
                            RecurrenceTheme = 3,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 2,
                            WhenOccurs = new DateTime(2023, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            Amount = 95.00m,
                            Description = "Waste Management Trash",
                            RecurrenceDayOfMonth = 30,
                            RecurrenceInterval = 3,
                            RecurrenceOrdinal = 0,
                            RecurrenceTheme = 3,
                            ReminderTheme = 1,
                            TransactionFromAccountId = 2,
                            WhenOccurs = new DateTime(2023, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Mayflower.Core.DomainModels.ReminderTheme", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("ReminderTheme", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "Error",
                            Value = "Error"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Bill Payment",
                            Value = "Bill"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Income",
                            Value = "Income"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Transfer",
                            Value = "Transfer"
                        });
                });

            modelBuilder.Entity("Mayflower.Core.DomainModels.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ExternalTransactionId")
                        .IsRequired()
                        .HasColumnType("varchar(125)");

                    b.Property<int>("FinancialAccountId")
                        .HasColumnType("int");

                    b.Property<string>("Memo")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RefNumber")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("WhenPosted")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FinancialAccountId");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("Mayflower.Core.DomainModels.TransactionTheme", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("TransactionTheme", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "None",
                            Value = "None"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Withdraw",
                            Value = "Withdraw"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Deposit",
                            Value = "Deposit"
                        });
                });

            modelBuilder.Entity("Mayflower.Core.DomainModels.FinancialAccount", b =>
                {
                    b.HasOne("Mayflower.Core.DomainModels.FinancialAccountTheme", "_financialAccountTheme")
                        .WithMany()
                        .HasForeignKey("FinancialAccountTheme")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mayflower.Core.DomainModels.FinancialInstitution", "FinancialInstitution")
                        .WithMany()
                        .HasForeignKey("FinancialInstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialInstitution");

                    b.Navigation("_financialAccountTheme");
                });

            modelBuilder.Entity("Mayflower.Core.DomainModels.Reminder", b =>
                {
                    b.HasOne("Mayflower.Core.DomainModels.RecurrenceDayOfWeek", "_recurrenceDayOfWeek")
                        .WithMany()
                        .HasForeignKey("RecurrenceDayOfWeek");

                    b.HasOne("Mayflower.Core.DomainModels.RecurrenceOrdinal", "_recurrenceOrdinal")
                        .WithMany()
                        .HasForeignKey("RecurrenceOrdinal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mayflower.Core.DomainModels.RecurrenceTheme", "_recurrenceTheme")
                        .WithMany()
                        .HasForeignKey("RecurrenceTheme")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mayflower.Core.DomainModels.ReminderTheme", "_reminderTheme")
                        .WithMany()
                        .HasForeignKey("ReminderTheme")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mayflower.Core.DomainModels.FinancialAccount", "TransactionFromAccount")
                        .WithMany()
                        .HasForeignKey("TransactionFromAccountId");

                    b.HasOne("Mayflower.Core.DomainModels.FinancialAccount", "TransactionToAccount")
                        .WithMany()
                        .HasForeignKey("TransactionToAccountId");

                    b.Navigation("TransactionFromAccount");

                    b.Navigation("TransactionToAccount");

                    b.Navigation("_recurrenceDayOfWeek");

                    b.Navigation("_recurrenceOrdinal");

                    b.Navigation("_recurrenceTheme");

                    b.Navigation("_reminderTheme");
                });

            modelBuilder.Entity("Mayflower.Core.DomainModels.Transaction", b =>
                {
                    b.HasOne("Mayflower.Core.DomainModels.FinancialAccount", "FinancialAccount")
                        .WithMany()
                        .HasForeignKey("FinancialAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
