// <auto-generated />
using System;
using Mayflower.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mayflower.Data.Migrations
{
    [DbContext(typeof(MayflowerContext))]
    [Migration("20230428204320_InitialCreationAndSeed")]
    partial class InitialCreationAndSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mayflower.DomainModels.RecurrenceDayOfWeek", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("RecurrenceDayOfWeek", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "None",
                            Value = "None"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Sunday",
                            Value = "Sunday"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Monday",
                            Value = "Monday"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tuesday",
                            Value = "Tuesday"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Wednesday",
                            Value = "Wednesday"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Thursday",
                            Value = "Thursday"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Friday",
                            Value = "Friday"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Saturday",
                            Value = "Saturday"
                        });
                });

            modelBuilder.Entity("Mayflower.DomainModels.RecurrenceOrdinal", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("RecurrenceOrdinal", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "None",
                            Value = "None"
                        },
                        new
                        {
                            Id = 1,
                            Name = "First",
                            Value = "First"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Second",
                            Value = "Second"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Third",
                            Value = "Third"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fourth",
                            Value = "Fourth"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Last",
                            Value = "Last"
                        });
                });

            modelBuilder.Entity("Mayflower.DomainModels.RecurrenceTheme", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("RecurrenceTheme", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "No Recurrence",
                            Value = "NoRecurrence"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Daily",
                            Value = "Daily"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Weekly",
                            Value = "Weekly"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Monthly",
                            Value = "Monthly"
                        });
                });

            modelBuilder.Entity("Mayflower.DomainModels.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecurrenceTheme")
                        .HasColumnType("int")
                        .HasColumnName("RecurrenceThemeId");

                    b.Property<int>("Theme")
                        .HasColumnType("int")
                        .HasColumnName("ReminderThemeId");

                    b.Property<int>("TransactionAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WhenToStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RecurrenceTheme");

                    b.HasIndex("Theme");

                    b.HasIndex("TransactionAccountId");

                    b.ToTable("Reminder", (string)null);
                });

            modelBuilder.Entity("Mayflower.DomainModels.ReminderTheme", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("ReminderTheme", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "Unknown",
                            Value = "Unknown"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Bill",
                            Value = "Bill"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Transfer",
                            Value = "Transfer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Income",
                            Value = "Income"
                        });
                });

            modelBuilder.Entity("Mayflower.DomainModels.TransactionAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountVendor")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NickName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("TransactionAccountThemeId");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.ToTable("TransactionAccount", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountVendor = "Ally Bank",
                            NickName = "Primary Checking",
                            Number = "1032497347",
                            Type = 2
                        },
                        new
                        {
                            Id = 2,
                            AccountVendor = "Ally Bank",
                            NickName = "Bill Pay Account",
                            Number = "1054452618",
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            AccountVendor = "Ally Bank",
                            NickName = "Primary Savings",
                            Number = "2132880598",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            AccountVendor = "Ally Bank",
                            NickName = "Xmas Fund",
                            Number = "2133086542",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            AccountVendor = "Ally Bank",
                            NickName = "Me-want Fund",
                            Number = "2141652087",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            AccountVendor = "Ally Bank",
                            NickName = "Birthday Fund",
                            Number = "2144275472",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            AccountVendor = "Ally Bank",
                            NickName = "Graces Emergency Fund",
                            Number = "2144275977",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            AccountVendor = "Ally Bank",
                            NickName = "Landscaping Fund",
                            Number = "2148132695",
                            Type = 1
                        });
                });

            modelBuilder.Entity("Mayflower.DomainModels.TransactionAccountTheme", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("TransactionAccountTheme", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "None",
                            Value = "None"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Savings",
                            Value = "Savings"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Checking",
                            Value = "Checking"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Marketing",
                            Value = "Marketing"
                        });
                });

            modelBuilder.Entity("Mayflower.DomainModels.TransactionTheme", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("TransactionTheme", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "None",
                            Value = "None"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Withdraw",
                            Value = "Withdraw"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Deposit",
                            Value = "Deposit"
                        });
                });

            modelBuilder.Entity("Mayflower.DomainModels.Reminder", b =>
                {
                    b.HasOne("Mayflower.DomainModels.RecurrenceTheme", "_recurrenceTheme")
                        .WithMany()
                        .HasForeignKey("RecurrenceTheme")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mayflower.DomainModels.ReminderTheme", "_reminderTheme")
                        .WithMany()
                        .HasForeignKey("Theme")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mayflower.DomainModels.TransactionAccount", "TransactionAccount")
                        .WithMany()
                        .HasForeignKey("TransactionAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransactionAccount");

                    b.Navigation("_recurrenceTheme");

                    b.Navigation("_reminderTheme");
                });

            modelBuilder.Entity("Mayflower.DomainModels.TransactionAccount", b =>
                {
                    b.HasOne("Mayflower.DomainModels.TransactionAccountTheme", "_transactionAccountTheme")
                        .WithMany()
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_transactionAccountTheme");
                });
#pragma warning restore 612, 618
        }
    }
}
